### ISSUE TITLE
autoCollapse conflicts with click behavior

### ISSUE THREAD

**Issue by yomed** [makeup-js/makeup-expander#1]
I'm currently using this as `new Expander(this.el, {click: true});`, so only passing in `click` config. From the current defaults, I also pick up `autoCollapse: true`. It seems that these may conflict. Here are the repro steps:
1. Click menu trigger (expands content)
2. Click a menu item (item takes focus)
3. Click menu trigger

I would expect step 3 to collapse the menu. When the focus leaves the item, it initially triggers a collapse per https://github.com/makeup-js/makeup-expander/blob/281b1d332e0480c3bf356e8efb0c681ef59ac0ce/src/index.js#L60-L62
But then the click event also gets triggered, which expands it again.

**Comment by ianmcburnie** [comment]
Thanks @yomed. Will take a look.

**Comment by ianmcburnie** [comment]
The bug lies in the makeup-exit-emitter dependency. Clicking menu trigger in step 3 should not emit a focusExit event like it currently does, which in turn causes expander to collapse. Will fix.

**Comment by ianmcburnie** [comment]
@yomed, can you try upgrading to v0.1.0? Note that `autoCollapse` has now been set to false by default, and that events were renamed to `expanderExpand` and `expanderCollapse` (we will rename these again, when we get consensus).

**Comment by yomed** [comment]
Thanks @ianmcburnie , that fixed the main issue. Changing the event names actually caused another issue (that's somewhat related).

I'm using the events like this, in order to easily catch them with Marko:
```marko
<span w-bind w-on-expanderExpand="handleExpand" w-on-expanderCollapse="handleCollapse">
```

The camelCase custom events should work fine, per https://github.com/marko-js/marko-widgets/issues/19

I believe there is a bug in marko-widgets, because it is incorrectly transforming the events to `expanderexpand` and `expandercollapse`. I would open an issue there... but marko-widgets doesn't really have active development anymore. We might want to consider this issue when deciding the final names.

**Comment by yomed** [comment]
@ianmcburnie Should the new event names be `expander-expand` and `expander-collapse`?

**Comment by ianmcburnie** [comment]
Yep. I was holding back on renaming all the makeup events, because well... it's a bit of a manual chore, but if the camel case is causing an actual issue with Marko I guess I should stop being lazy and rename them... starting with this one :-)

**Comment by ianmcburnie** [comment]
v0.2.0 published with new event names.
