### ISSUE TITLE
Create a "destroy" or "clean up" method for event listeners

### ISSUE THREAD

**Issue by seangates** [makeup-js/makeup-expander#10]
When this utility has created event listeners for things like document touch events, or focus events, they may not get removed when the component has been destroyed (say, by Marko). This causes issues when they are still attached to components but the makeup utility that created them no longer exists.

As a reference, @DylanPiercey created a utility to help manage listeners, and easily cancel all of them in one fell swoop: https://github.com/marko-js/utils/blob/master/packages/abort-group/README.md

**Comment by ianmcburnie** [comment]
Good spot. I still need to add destroy to nearly all of the new makeup modules. Here's the pattern I like to follow:

https://github.com/eBay/mindpatterns/blob/gh-pages/_js/accordion-legacy.es6.js#L84

**Comment by ianmcburnie** [comment]
`cancelAsync` was added in 0.7.0 to help with the Marko issue. In future I think we should rename this to something less cryptic, like `disable` (as it disables all listeners). We could even add a `enable` method then that picks it up from where it was before being disabled. Anyhow, I still see a need for a destroy method to, so I'll leave this ticket open for me to do.
