### ISSUE TITLE
expander default state

### ISSUE THREAD

**Issue by yomed** [makeup-js/makeup-expander#2]
Currently it looks like expander assumes that the content is closed by default, but shouldn't it first use the existing `aria-expanded` value if it exists?

https://github.com/makeup-js/makeup-expander/blob/1b2a1b3c914ac8a04fa45376d23f5dc50603a0e5/src/index.js#L46

**Comment by ianmcburnie** [comment]
Yeah, that would make sense. Will fix.

**Comment by ianmcburnie** [comment]
Fixed in v0.2.1
