### ISSUE TITLE
.babelrc could get picked up by bundlers

### ISSUE THREAD

**Issue by yomed** [makeup-js/makeup-expander#5]
When an app uses `lasso-babel-transform`, it will attempt to transform any `node_modules/` packages that has a `.babelrc` file. In this case, it sees the `.babelrc` in `makeup-expander/` and attempts to compile it, then runs into an error requiring `babel-plugin-transform-object-assign` because that is currently a devDependency rather than a dependency. Since the code here is already compiled, we wouldn't want it to get transformed anyway, so the simple fix is to exclude `.babelrc` via `.npmignore` blacklist or `files: []` whitelist.

I did not make a PR, because I imagine this affects many/all of the `makeup` repos.

We may also want to consider changing this behavior in https://github.com/lasso-js/lasso-babel-transform

cc @mlrawlings

**Comment by ianmcburnie** [comment]
Fixed, thanks. I'll go through the others too.
