### ISSUE TITLE
Add `hostContainerClass` and `simulateSpacebarClick` options to readme

### ISSUE THREAD

**Issue by darkwebdev** [makeup-js/makeup-expander#8]
Both `hostContainerClass` and `simulateSpacebarClick` can be used as options properties, but not documented yet.

**Comment by darkwebdev** [comment]
@seangates @ianmcburnie guys, could you please update the docs, I will then update the TypeScript definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/makeup-expander/index.d.ts

thanks!

**Comment by ianmcburnie** [comment]
Sorry @darkwebdev, I've missed a few of these issue requests, and now only just stumbled upon this one. We are making a couple of changes to the way hostContainerClass works. We will update the docs as part of the next release accordingly.

**Comment by ianmcburnie** [comment]
Updated README. Closing.
